
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 13 22:35:11 CET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class TreeSymbol {
  /* terminals */
  public static final int DIVIDE = 17;
  public static final int FLOTTANT = 37;
  public static final int CHAR = 33;
  public static final int LACC = 27;
  public static final int CAR = 39;
  public static final int SEMIC = 19;
  public static final int BOOLEEN = 38;
  public static final int INT = 28;
  public static final int VIRGULE = 21;
  public static final int FOR = 24;
  public static final int MINUS = 15;
  public static final int AND = 3;
  public static final int RPAR = 13;
  public static final int OR = 2;
  public static final int BOOL = 30;
  public static final int NON = 10;
  public static final int PLUS = 14;
  public static final int MAIN = 20;
  public static final int EQUI = 11;
  public static final int IF = 22;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int error = 1;
  public static final int RACC = 26;
  public static final int IMP = 9;
  public static final int NUMBER = 36;
  public static final int UNSIGNED = 31;
  public static final int EQ = 8;
  public static final int TIMES = 16;
  public static final int PGS = 7;
  public static final int ELSE = 23;
  public static final int PPS = 6;
  public static final int WHILE = 25;
  public static final int FLOAT = 29;
  public static final int PGE = 5;
  public static final int LPAR = 12;
  public static final int STRING = 32;
  public static final int MINUS_U = 18;
  public static final int CHAINE = 40;
  public static final int PPE = 4;
}

